- .github/workflows/main.yml
Use Ruby 3.2
Baxkport of:
- https://github.com/rubocop/rubocop-rspec/pull/1531
- https://github.com/rubocop/rubocop-rspec/pull/1529
> Use Ruby 3.2

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/main.yml
- CHANGELOG.md
- docs/modules/ROOT/pages/cops_capybara.adoc
- lib/rubocop/cop/capybara/current_path_expectation.rb
- rubocop-capybara.gemspec
- tasks/cut_release.rake
It happened that the primary branch of this repo is `main`. Adjust every mention of it.
> Master -> Main

- README.md
> Add a link to Capybara

- spec/rubocop/cop/capybara/current_path_expectation_spec.rb
This PR is remove unnecessary escapes.
> Remove unnecessary escapes

- CHANGELOG.md
This PR is fix a typo in the changelog.
> Fix a typo in the changelog

- .rubocop.yml
Follow up: https://github.com/rubocop/rubocop/commit/6d45fd50dba01277a0c34a52ff37c47cff30b15c
> Add settings for typo suppression

- .rubocop.yml
- lib/rubocop/cop/capybara/current_path_expectation.rb
Follow up: https://github.com/rubocop/rubocop-rspec/pull/1579
> Enable some new cops

- CHANGELOG.md
The release date has been delayed and has been corrected. Sorry.
> Fix the release date

- docs/modules/ROOT/pages/index.adoc
This PR is add a link to Capybara in the documentation.
> Add a link to Capybara in the documentation

- .simplecov
- CHANGELOG.md
- Rakefile
- config/default.yml
- docs/modules/ROOT/pages/cops.adoc
- docs/modules/ROOT/pages/cops_capybara_rspec.adoc
- lib/rubocop/capybara/config_formatter.rb
- lib/rubocop/cop/capybara/rspec/predicate_matcher.rb
- lib/rubocop/cop/capybara_cops.rb
- spec/project/default_config_spec.rb
- spec/rubocop/cop/capybara/rspec/predicate_matcher_spec.rb
- tasks/cops_documentation.rake
Re-targeting: https://github.com/rubocop/rubocop-rspec/pull/1495
> Add new `Capybara/RSpec/PredicateMatcher` cop

- .rubocop.yml
- spec/rubocop/cop/capybara/current_path_expectation_spec.rb
Follow up: https://github.com/rubocop/rubocop-rspec/pull/1680
> Use offense instead of violation

- CHANGELOG.md
- config/default.yml
- docs/antora.yml
- docs/modules/ROOT/pages/cops_capybara.adoc
- docs/modules/ROOT/pages/cops_capybara_rspec.adoc
- lib/rubocop/capybara/version.rb
It has been more than about 5 months since the last time and it is time to release the next version.
> Bump version v2.19.0

- docs/modules/ROOT/nav.adoc
Fix: https://github.com/rubocop/rubocop-capybara/issues/73
> Add RSpec department in documentation

- .github/workflows/danger.yml
- .github/workflows/main.yml
> Add Ruby 3.3 to CI matrix

- CHANGELOG.md
- config/default.yml
- docs/antora.yml
- docs/modules/ROOT/pages/cops_capybara.adoc
- lib/rubocop/capybara/version.rb
> Bump version v2.20.0

- spec/rubocop/cop/capybara/negation_matcher_spec.rb
> Fix string interpolation that was not working in example text

- .github/workflows/main.yml
Follow up: https://github.com/rubocop/rubocop-rspec/pull/1817
> CI: Fix the RSpec 4 job

- docs/modules/ROOT/pages/cops_capybara.adoc
- docs/modules/ROOT/pages/cops_capybara_rspec.adoc
> Generate cops documentation

- .rubocop.yml
- Gemfile
> Bump rubocop-rspec to 2.29.2 and enable new cops

- Rakefile
- lib/rubocop/capybara/cop/generator.rb
before:
```
Do 4 steps:
1. Modify the description of Capybara/CopName in config/default.yml
2. Implement your new cop in the generated file!
3. Commit your new cop with a message such as
e.g. "Add new `Capybara/CopName` cop"
4. Run `bundle exec rake changelog:new` to generate a changelog entry
```
after:
```
Do 4 steps:
1. Modify the description of Capybara/CopName in config/default.yml
2. Implement your new cop in the generated file!
3. Commit your new cop with a message such as
e.g. "Add new `Capybara/CopName` cop"
4. Add an entry about new cop to CHANGELOG.md
```
- [-] Added an entry to the `CHANGELOG.md` if …
> Change step with new_cop command for rubocop-capybara

- CHANGELOG.md
- docs/antora.yml
- lib/rubocop/capybara/version.rb
> Release v2.21.0

- .rubocop.yml
- Gemfile
> Remove unnecessary RuboCop RSpec settings

- .github/workflows/danger.yml
- .github/workflows/main.yml
Ruby 3.4 has been released🎉
https://www.ruby-lang.org/en/news/2024/12/25/ruby-3-4-0-released/
> Update Ruby version in GitHub Actions workflow to 3.4

- .simplecov
- lib/rubocop/cop/capybara/click_link_or_button_style.rb
- lib/rubocop/cop/capybara/negation_matcher.rb
- lib/rubocop/cop/capybara/rspec/predicate_matcher.rb
> Instruct SimpleCov to ignore unreachable code

- CHANGELOG.md
- config/default.yml
- docs/antora.yml
- docs/modules/ROOT/pages/cops_capybara.adoc
- lib/rubocop/capybara/version.rb
Let’s publish a plugin’ed version ✨ 
> Release v2.22.0
