rubocop/rubocop-capybara

- CHANGELOG.md
- config/default.yml
- docs/antora.yml
- docs/modules/ROOT/pages/cops_capybara.adoc
> Release 2.17.0

- docs/antora.yml
Following [this checklist](https://github.com/rubocop/rubocop-capybara/pull/2#issuecomment-1367335974)
> Switch back Antora to ~ version

- docs/modules/ROOT/pages/usage.adoc
Currently, `**/test/**/*` is also inspected by `rubocop-capybara`, so I modified it accordingly.
Ref: https://github.com/rubocop/rubocop-capybara/blob/10e2d89cf876888dcca3c473a7c69cc6b5cb93cc/config/default.yml#L8
> Fix errors in documentation for file paths to be inspected

- .github/workflows/codespell.yml
- .github/workflows/linting.yml
- .github/workflows/main.yml
Same as: https://github.com/rubocop/rubocop-rspec/pull/1539
This PR ensures that only the last execution per branch always works, even when pushed multiple times in a row, for example. The older one is canceled.
Refs:
https://docs.github.com/en/actions/using-jobs/using-concurrency https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
> Use concurrency for GitHub Actions workflow

- CHANGELOG.md
- lib/rubocop/cop/capybara/current_path_expectation.rb
- spec/rubocop/cop/capybara/current_path_expectation_spec.rb
This PR is fix an incorrect autocorrect for `Capybara/PathExpectation`.
```diff
-expect(page).to have_current_path `pwd`
+expect(page).to have_current_path `pwd`, ignore_query: true
expect(page).to have_current_path "/callback" \
-                            "/foo"
+                            "/foo", ignore_query: true
```
> Fix an incorrect autocorrect for `Capybara/PathExpectation`

- .github/workflows/codespell.yml
- .github/workflows/linting.yml
- .github/workflows/main.yml
Same as: https://github.com/rubocop/rubocop-rspec/pull/1544 https://github.com/rubocop/rubocop/pull/11414
The following are included as keys to the group.
`${{ github.head_ref || github.run_id }}`
This allows concurrency to work only with Push to PullRequest, and cancels all but the most recent push for successive pushes; for merge commits, in other words push events, `${{ github.run_id }}` is used, so The cancellation is not enforced because it is always a unique group.
This eliminates the problem of consecutive Pushes being cancelled at the time of release.
- [-] Added an entry to the `CHANGELOG.md` if the …
> Apply concurrency for GHA workflow `pull_requests` events only

- .rubocop.yml
- CHANGELOG.md
- lib/rubocop/cop/capybara/mixin/capybara_help.rb
- lib/rubocop/cop/capybara/mixin/css_selector.rb
- lib/rubocop/cop/capybara/specific_actions.rb
- lib/rubocop/cop/capybara/specific_finders.rb
- lib/rubocop/cop/capybara/specific_matcher.rb
- spec/rubocop/cop/capybara/mixin/css_selector_spec.rb
- spec/rubocop/cop/capybara/specific_actions_spec.rb
- spec/rubocop/cop/capybara/specific_finders_spec.rb
- spec/rubocop/cop/capybara/specific_matcher_spec.rb
Fix: https://github.com/rubocop/rubocop-capybara/issues/4
> Fix a false positive and incorrect autocorrect for `Capybara/SpecificActions`, `Capybara/SpecificFinders` and `Capybara/SpecificMatcher`

- config/default.yml
- docs/modules/ROOT/pages/usage.adoc
In this PR we are going to add the file path where cucumber test files are located to the default Include.
Ref: https://github.com/cucumber/cucumber-ruby#initialization
> Add path to support cucumber in Include

- CHANGELOG.md
- lib/rubocop/capybara/version.rb
A month has passed since the [last release](https://github.com/rubocop/rubocop-capybara/pull/2), so let's move on to the next version.
> Bump version to v2.17.1

- lib/rubocop/cop/capybara/specific_actions.rb
- lib/rubocop/cop/capybara/specific_finders.rb
This PR correct offenses for `InternalAffairs/LocationExpression` and `InternalAffairs/RedundantSourceRange`.
```
Offenses:
lib/rubocop/cop/capybara/specific_actions.rb:78:52: C: [Corrected] InternalAffairs/LocationExpression: Use source_range instead.
receiver.loc.selector.with(end_pos: node.loc.expression.end_pos)
^^^^^^^^^^^^^^
lib/rubocop/cop/capybara/specific_finders.rb:71:51: C: [Corrected] InternalAffairs/LocationExpression: Use source_range instead.
corrector.replace(node.first_argument.loc.expression,
^^^^^^^^^^^^^^
lib/rubocop/cop/capybara/specific_finders.rb:120:18: C: [Corrected] InternalAffairs/LocationExpression: Use source_range instead.
node.loc.expression.end_pos
^^^^^^^^^^^^^^
33 files inspected, 3 offenses detected, 3 offenses corrected
```
```
Offenses: …
```
> Correct offenses for `InternalAffairs`

- .github/workflows/codespell.yml
How about checking about codespell for hidden files (those starting with ".") as well? 
https://github.com/codespell-project/actions-codespell#parameter-check_hidden
> Add an option to the actions-codespell configuration to check hidden files

- docs/modules/ROOT/pages/cops_capybara.adoc
- lib/rubocop/cop/capybara/current_path_expectation.rb
I noticed some broken links while browsing the capybara manual ([here](https://docs.rubocop.org/rubocop-capybara/cops_capybara.html#capybaracurrentpathexpectation)). This PR fixes them.
Perhaps capybara's default branch used to be `main`? I'm not sure... but presently it is `master`, and so these links need to be updated.
> Fix a few broken links in docs

- CHANGELOG.md
- lib/rubocop/cop/capybara/specific_finders.rb
- spec/rubocop/cop/capybara/specific_finders_spec.rb
Resolve: https://github.com/rubocop/rubocop-capybara/issues/23#issuecomment-1481609845
This PR is fix an offense message for `Capybara/SpecificFinders`. Modify the message of the offense as follows:
```diff
find('#some-id')
-      ^^^^^^^^^^^^^^^^ Prefer `find_by` over `find`.
+      ^^^^^^^^^^^^^^^^ Prefer `find_by_id` over `find`.
```
> Fix an offense message for `Capybara/SpecificFinders`

- .github/workflows/mdformat.yml
- .github/workflows/yamllint.yml
This PR remove filtering by `paths`.
We have made it our policy to have a conversation here and remove control by `paths`.
- https://github.com/rubocop/rubocop-capybara/pull/40#discussion_r1167681129
> Fix the issue of blocking merge when making it required

- CHANGELOG.md
- lib/rubocop/cop/capybara/negation_matcher.rb
- spec/rubocop/cop/capybara/negation_matcher_spec.rb
Added `content` to the list of matchers for `Capybara/NegationMatcher`. 
It allows said cop to check for `not_to have_content`, correct it to `to have_no_content` and vice versa.
`have_content` is not included in Capybara list of `have_no_..` matchers but is rather aliased to `have_no_text`. ([source](https://github.com/teamcapybara/capybara/blob/c8d3ff5f9b768428d5b2013931cc92ffa324b88b/lib/capybara/rspec/matchers.rb#L169)). 
I'm not sure if thats perhaps a problem for this PR`s change. Maybe a different approach has to be taken due to above said.
> Expand `Capybara/NegationMatcher` to support `have_content`

- CHANGELOG.md
- lib/rubocop/cop/capybara/current_path_expectation.rb
- spec/rubocop/cop/capybara/current_path_expectation_spec.rb
Fix: https://github.com/rubocop/rubocop-capybara/issues/37
> Fix an incorrect autocorrect for `Capybara/CurrentPathExpectation` when matcher's argument is a method with a argument and no parentheses

- CHANGELOG.md
- docs/antora.yml
- lib/rubocop/capybara/version.rb
A few months have passed since the [last release](https://github.com/rubocop/rubocop-capybara/releases/tag/v2.17.1), so let's move on to the next version.
> Bump version to v2.18.0

- .rubocop.yml
- Gemfile
This PR add missing pending rubocop-rspec cops in v2.20.0.
> Add missing pending rubocop-rspec cops in v2.20.0

- spec/rubocop/cop/capybara/match_style_spec.rb
- spec/rubocop/cop/capybara/negation_matcher_spec.rb
- spec/rubocop/cop/capybara/specific_actions_spec.rb
- spec/rubocop/cop/capybara/specific_finders_spec.rb
Previously, in `rubocop-rspec`, this was needed to have control over "config" shared context
inclusion. We wanted to include ours, but not the one from `rubocop`.
Sibling to https://github.com/rubocop/rubocop-factory_bot/pull/21 and https://github.com/rubocop/rubocop-rspec/pull/1640
Thanks @r7kamura!
**Replace this text with a summary of the changes in your PR. The more detailed you are, the better.**
> Remove redundant config metadata

- docs/modules/ROOT/pages/index.adoc
Follow up: https://github.com/rubocop/rubocop-factory_bot/pull/27
> Use U+002d instead of U+2013

- .github/workflows/danger.yml
- Dangerfile
- Gemfile
Follow up: https://github.com/rubocop/rubocop-rspec/pull/1617
> Add a Danger check to prevent review approval for cops that have become `Enabled: true`

- docs/modules/ROOT/pages/cops_capybara.adoc
- lib/rubocop/cop/capybara/specific_finders.rb
Fixed bad case since it is not a violation if there is an attribute other than id.
> Fix an errors in `Capybara/SpecificFinders` documentation

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_capybara.adoc
- lib/rubocop/cop/capybara/specific_finders.rb
- spec/rubocop/cop/capybara/specific_finders_spec.rb
Support the following cases:
```ruby
find(:css, '#some-id')
```
> Fix a false positive for `Capybara/SpecificFinders` when `find` with kind option

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops.adoc
- docs/modules/ROOT/pages/cops_capybara_rspec.adoc
- lib/rubocop/cop/capybara/rspec/have_selector.rb
- lib/rubocop/cop/capybara_cops.rb
- spec/rubocop/cop/capybara/rspec/have_selector_spec.rb
This PR add new `Capybara/RSpec/HaveSelector` cop.
```ruby
expect(foo).to have_selector(:css, 'bar')
expect(foo).to have_css('bar')
expect(foo).to have_selector(:xpath, 'bar')
expect(foo).to have_xpath('bar')
expect(foo).to have_selector('bar')
expect(foo).to have_css('bar')
expect(foo).to have_selector('bar')
expect(foo).to have_xpath('bar')
```
> Add new `Capybara/RSpec/HaveSelector` cop

- .simplecov
- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops.adoc
- docs/modules/ROOT/pages/cops_capybara.adoc
- lib/rubocop/cop/capybara/click_link_or_button_style.rb
- lib/rubocop/cop/capybara_cops.rb
- spec/rubocop/cop/capybara/click_link_or_button_style_spec.rb
Fix: https://github.com/rubocop/rubocop-capybara/issues/58
> Add new `Capybara/ClickLinkOrButtonStyle` cop

- CHANGELOG.md
- spec/project/changelog_spec.rb
Follow up: https://github.com/rubocop/rubocop-rspec/pull/1721
> Improve for project_spec

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_capybara.adoc
- lib/rubocop/cop/capybara/current_path_expectation.rb
- spec/rubocop/cop/capybara/current_path_expectation_spec.rb
Fix: https://github.com/rubocop/rubocop-capybara/issues/50
> Fix an incorrect autocorrect for `Capybara/CurrentPathExpectation`

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_capybara.adoc
- lib/rubocop/cop/capybara/click_link_or_button_style.rb
Fix: https://github.com/rubocop/rubocop-capybara/pull/61#issuecomment-1727556658
Fix: https://github.com/rubocop/rubocop-capybara/pull/61#issuecomment-1740641746
> Change to default `EnforcedStyle: link_or_button` for `Capybara/ClickLinkOrButtonStyle` cop

- CHANGELOG.md
- lib/rubocop/cop/capybara/rspec/have_selector.rb
- spec/rubocop/cop/capybara/rspec/have_selector_spec.rb
partially fixed: https://github.com/rubocop/rubocop-capybara/issues/78
> Fix a false negative for `RSpec/HaveSelector` when first argument is dstr node

- lib/rubocop/cop/capybara/specific_finders.rb
❯ bundle exec rubocop -A
Inspecting 40 files
.................C......................
Offenses:
lib/rubocop/cop/capybara/specific_finders.rb:79:30: C: [Corrected] InternalAffairs/NodeFirstOrLastArgument: Use #first_argument instead of #arguments[0].
range_between(node.arguments[0].source_range.end_pos,
^^^^^^^^^^^^
40 files inspected, 1 offense detected, 1 offense corrected
> Correct a `InternalAffairs/NodeFirstOrLastArgument`

- .rubocop.yml
- Gemfile
- lib/rubocop/cop/capybara/click_link_or_button_style.rb
Follow: https://github.com/rubocop/rubocop-rspec/pull/1744
> Enable a few pending cops

- CHANGELOG.md
- lib/rubocop-capybara.rb
- lib/rubocop/cop/capybara/mixin/css_attributes_parser.rb
- lib/rubocop/cop/capybara/mixin/css_selector.rb
- spec/rubocop/cop/capybara/mixin/css_attributes_parser_spec.rb
- spec/rubocop/cop/capybara/mixin/css_selector_spec.rb
- spec/rubocop/cop/capybara/specific_matcher_spec.rb
partially fixed: https://github.com/rubocop/rubocop-capybara/issues/78
following case:
```rb
have_css("input[name='post_author_attributes__first_name_']")
have_css("input[name='post[author_attributes][first_name]']")
```
> Fix an invalid attributes parse when name with multiple `[]`

- CHANGELOG.md
- config/default.yml
- docs/modules/ROOT/pages/cops_capybara.adoc
- lib/rubocop/cop/capybara/negation_matcher.rb
Fix: https://github.com/rubocop/rubocop-capybara/issues/57
> Change to default `EnforcedStyle: have_no` for `Capybara/NegationMatcher` cop

- CHANGELOG.md
- lib/rubocop/cop/capybara/specific_matcher.rb
- spec/rubocop/cop/capybara/specific_matcher_spec.rb
Fix: https://github.com/rubocop/rubocop-capybara/issues/82
> Fix a false positive for `Capybara/SpecificMatcher` when `text:` or `exact_text:` with regexp

- lib/rubocop/cop/capybara/current_path_expectation.rb
- lib/rubocop/cop/capybara/specific_actions.rb
- lib/rubocop/cop/capybara/specific_matcher.rb
- rubocop-capybara.gemspec
- spec/rubocop/capybara/description_extractor_spec.rb
- spec/rubocop/cop/capybara/current_path_expectation_spec.rb
- spec/rubocop/cop/capybara/specific_actions_spec.rb
- spec/rubocop/cop/capybara/specific_matcher_spec.rb
- spec/rubocop/cop/capybara/visibility_matcher_spec.rb
Follow up: rubocop/rubocop-rspec#1761
> Use squiggly heredocs wherever possible

- CHANGELOG.md
- lib/rubocop/cop/capybara/negation_matcher.rb
- spec/rubocop/cop/capybara/negation_matcher_spec.rb
Fix: https://github.com/rubocop/rubocop-capybara/issues/90
> Fix a false negative for `Capybara/NegationMatcher` when using `to_not `

- lib/rubocop/cop/capybara/mixin/css_attributes_parser.rb
Fix: https://github.com/rubocop/rubocop-capybara/issues/100
> Use String#each_char instead of String#chars

- spec/rubocop/cop/capybara/specific_actions_spec.rb
- spec/rubocop/cop/capybara/specific_matcher_spec.rb
https://github.com/rubocop/rubocop-capybara/actions/runs/7914278306/job/21603687443?pr=104
> Fix an offense for InternalAffairs/RedundantExpectOffenseArguments

- .github/workflows/main.yml
Follow up rubocop/rubocop-ast#277
> Add job for CI using Prism parser

- CHANGELOG.md
- docs/modules/ROOT/pages/cops_capybara.adoc
- lib/rubocop/cop/capybara/specific_finders.rb
- spec/rubocop/cop/capybara/specific_finders_spec.rb
Support cases that `find` the following `id`:
```
page.html # => '<input id="field">'
page.find :id, 'field'
```
> Fix a false negative for `Capybara/SpecificFinders` when using `find(:id, 'some-id')`

- docs/modules/ROOT/pages/cops_capybara.adoc
- lib/rubocop/cop/capybara/specific_matcher.rb
> Fix example code in the `SpecificMatcher` cop

- docs/modules/ROOT/pages/cops.adoc
- tasks/cut_release.rake
This PR fixes some rubocop offenses
```
tasks/cut_release.rake:41:21: W: [Corrected] Lint/ImplicitStringConcatenation: Combine '\0' and "## #{version} (#{Time.now.strftime('%F')})\n\n" into a single string literal, rather than using implicit string concatenation. Or, if they were intended to be separate method arguments, separate them with a comma.
'\0' "## #{version} (#{Time.now.strftime('%F')})\n\n")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tasks/cut_release.rake:41:21: C: [Corrected] Style/StringConcatenation: Prefer string interpolation to string concatenation.
'\0' + "## #{version} (#{Time.now.strftime('%F')})\n\n")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
Before submitting the PR …
> Fix some rubocop offenses

- spec/rubocop/capybara/description_extractor_spec.rb
```
RuboCop::Capybara::DescriptionExtractor
builds a hash of descriptions (FAILED - 1)
Failures:
1) RuboCop::Capybara::DescriptionExtractor builds a hash of descriptions
Failure/Error:
expect(described_class.new(yardocs).to_h).to eql(
'Capybara/Foo'          => { 'Description' => 'Checks foo' },
'Capybara/Undocumented' => { 'Description' => ''           }
)
expected: {"Capybara/Foo"=>{"Description"=>"Checks foo"}, "Capybara/Undocumented"=>{"Description"=>""}}
got: {"Capybara/AmbiguousClick"=>{"Description"=>"Specify the exact target to click on."}, "Capybara/Click..."Capybara/VisibilityMatcher"=>{"Description"=>"Checks for boolean visibility in Capybara finders."}}
(compared using eql?)
Diff:
@@ -1,3 +1,16 @@
+"Capybara/AmbiguousClick" => {"Description"=>"Specify the exact target to click …
```
> Fix the flaky test for spec/rubocop/capybara/description_extractor_spec.rb

- CHANGELOG.md
- lib/rubocop/cop/capybara/rspec/have_selector.rb
- spec/rubocop/cop/capybara/rspec/have_selector_spec.rb
`ruby-lsp` constanty runs RuboCop over code while typing, so this error will just happen.
Do note that there are currently 2 RuboCop offenses introduced through new `rubocop` versions:
```
Offenses:
lib/rubocop/cop/capybara/rspec/have_selector.rb:82:30: C: InternalAffairs/UndefinedConfig: DefaultSelector is not defined in the configuration for Capybara/RSpec/HaveSelector in config/default.yml.
cop_config.fetch('DefaultSelector', 'css')
^^^^^^^^^^^^^^^^^
tasks/cut_release.rake:41:21: W: [Correctable] Lint/ImplicitStringConcatenation: Combine '\0' and "## #{version} (#{Time.now.strftime('%F')})\n\n" into a single string literal, rather than using implicit string concatenation. Or, if they were intended to be separate method arguments, separate them with a comma.
'\0' "## #{version} …
```
> Fix an error for `Capybara/RSpec/HaveSelector` when passing no arguments

- docs/modules/ROOT/pages/cops_capybara.adoc
- docs/modules/ROOT/pages/cops_capybara_rspec.adoc
Use `bundle exec rake generate_cops_documentation `
> Update references and examples for Capybara cops in documentation

- lib/rubocop/cop/capybara/rspec/predicate_matcher.rb
`rubocop-ast` defines some node groups (https://github.com/rubocop/rubocop-ast/blob/85bfe84/lib/rubocop/ast/node.rb#L89-L116) that can be used in place of a union of node types.
> Use node groups in node patterns to replace unions of types

- CHANGELOG.md
- lib/rubocop-capybara.rb
`require_relative 'rubocop/capybara/version'` was missing, causing the constant lookup for `Version::STRING` in `lib/rubocop/capybara/plugin.rb` to resolve to `RuboCop::Version::STRING` instead of `RuboCop::Capybara::Version::STRING`.
This PR fixes an issue where `rubocop -V` incorrectly displayed the RuboCop version instead of the rubocop-capybara version:
```console
$ bundle exec rubocop -V
1.73.2 (using Parser 3.3.7.1, rubocop-ast 1.38.1, analyzing as Ruby 2.7, running on ruby 3.4.2) [x86_64-darwin23]
- rubocop-performance 1.24.0
- rubocop-rake 0.7.1
- rubocop-capybara 1.73.2
- rubocop-factory_bot 1.73.2
- rubocop-rspec_rails 2.31.0
- rubocop-rspec 3.5.0
```
Before submitting the PR make sure the following are …
> Fix incorrect plugin version

- docs/modules/ROOT/pages/cops_capybara.adoc
- lib/rubocop/cop/capybara/visibility_matcher.rb
Replace the adoc format link with a plain link that also works in rdoc. 
Reason: Rubocop itself links to 
https://www.rubydoc.info/gems/rubocop-capybara/RuboCop/Cop/Capybara/VisibilityMatcher 
which seems not to render the adoc format: 
> Fix format of link to Capybara docs
